sudo: required

language: generic

services:
  - docker

matrix:
  include:
    - os: linux
      env: BUILD=linux
    - os: linux
      env: BUILD=windows
    - os: osx
      env: BUILD=osx

git:
  # whether to recursively clone submodules
  submodules: true

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work
  - docker_images

before_cache:
  - docker image prune -f
  - docker save -o docker_images/images.tar $(docker images -a -q)

before_install:
  - docker load -i docker_images/images.tar || true
  - export TAG=$(git describe --abbrev=4 --dirty --always --tags)
  
  # create permission script 
  - echo '#!/bin/bash' > $TRAVIS_BUILD_DIR/setFolder.sh
  - echo 'mkdir -p       "$1"' >> $TRAVIS_BUILD_DIR/setFolder.sh
  - echo 'chown -R :6666 "$1"' >> $TRAVIS_BUILD_DIR/setFolder.sh
  - echo 'chmod -R 775   "$1"' >> $TRAVIS_BUILD_DIR/setFolder.sh
  - echo 'chmod -R g+s   "$1"' >> $TRAVIS_BUILD_DIR/setFolder.sh
  - chmod +x $TRAVIS_BUILD_DIR/setFolder.sh

  - $TRAVIS_BUILD_DIR/setFolder.sh .stack-work
  - $TRAVIS_BUILD_DIR/setFolder.sh .output
  - git submodule foreach --recursive "$TRAVIS_BUILD_DIR/setFolder.sh .stack-work"

  - ls -lah .
  - git submodule foreach --recursive "ls -la .stack-work"

install:
  - |
    set -ex
    case "$BUILD" in
      linux)
        docker build -t gamma_stack -f linux.Dockerfile .
        ;;
      windows)
        docker build -t gamma_stack -f wine.Dockerfile .
        ;;
      osx)
        mkdir -p ~/.local/bin
        export PATH=$HOME/.local/bin:$PATH
        travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
        stack --no-terminal --install-ghc --only-dependencies
        ;;
    esac
    set +ex

script:
  - |
    set -ex
    case "$BUILD" in
      osx)
        stack install --local-bin-path ".output/$BUILD-$TAG"
        ;;
      linux|windows)
        docker container run -v $(pwd):/appdata:Z gamma_stack:latest install --allow-different-user --local-bin-path ".output/$BUILD-$TAG"
        ;;
    esac
    set +ex

after_script:
  - docker images
  - docker ps

after_success:
  - ls -lah ".output/$BUILD-$TAG/"
  - for f in $(find .output/$BUILD-$TAG/* -maxdepth 0); do mv -v "$f" "$(dirname "$f")/$BUILD-$(basename "$f")-$TAG"; done

after_failure:
  - df -h
  - free -h

deploy:
  provider: releases
  api_key: "KcRecRX0xqKqreFsqiXxIOkIdBGyTVH3ZclV7tz/NpCCaWxLrYBFD6zwK23KR2lthI3MXXPs7S05uFQyYVfJaQP9/+LpxTHjAb0MyhzDIINBgvBlpC4qHMvWKJVM4sgp3DcxBxOeHWAfownpBQ410z5nJSsP14dTHmvtXGTY9epUSYTOUulrETu0zKoleV+B8TEdcpvdX+N6WcFiKFn2AZQaWu8bXqtSOgsMVU001Dk7D0GrzFYb6t0QSC2wYgcRdYpfD89jHLktB6oTgoc3yD1iToim/CDfnIcI4Pt6M7SuZmFzwqR6giBTmFTdHtD+hnYAra+YEHWTG7iq7gCs32sN27y9xeZ4O9ZYelp4/6esiMVm5BpkGzmtKdLVlAeIYisPW3WUCvm3k4rs2JWl6I54jU3XHz8h5yIzbZu6d1VldUO5tT+cRDQF4Xkd0qCjxkscdJJZ+lenkLifor7cDGZih0YJ8XzJZjxCOgERySXEulp/xuVmM0a8z3jWBUGyqnCwewW+klez9nj3BXRW/YFrn5N4kG/Ml0RqLQrJPAu7dCW+meNAX02m+ElsN6EYLFbp9Y/2Fal30Etsd3QN/UDKvYHTmG7v49ghcSJcWQwttdFXizwFpPqK/eX5TLKMJYatmdzRVWAkit4pGtsVrPenmVRjIt82maYNr2QCBXk="
  file: .output/$BUILD-$TAG/*
  skip_cleanup: true
  on:
    branch: master
    tags: true
