sudo: required

language: generic

services:
  - docker

matrix:
  include:
    - os: linux
      env: BUILD=linux
    - os: linux
      env: BUILD=windows
    - os: osx
      env: BUILD=osx
    - os: linux
      env: BUILD=docs

git:
  # whether to recursively clone submodules
  submodules: true

cache:
  directories:
  - $TRAVIS_BUILD_DIR/.docker_images
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work
  - $TRAVIS_BUILD_DIR/packages/hammer/.stack-work
  - $TRAVIS_BUILD_DIR/packages/linear-vect/.stack-work
  - $TRAVIS_BUILD_DIR/packages/mcl/.stack-work
  - $TRAVIS_BUILD_DIR/packages/queryforest/.stack-work
  - $TRAVIS_BUILD_DIR/packages/sledge/.stack-work
  - $TRAVIS_BUILD_DIR/packages/vtk/.stack-work

before_cache:
  - docker image prune -f
  - docker save -o $TRAVIS_BUILD_DIR/.docker_images/images.tar $(docker images -a -q)

before_install:
  - export TAG=$(git describe --abbrev=4 --dirty --always --tags)
  - echo "Tag $TAG"
  - echo "Tag $(id -u)"
  
  - docker load -i $TRAVIS_BUILD_DIR/.docker_images/images.tar || true
  
  # create permission script 
  - echo '#!/bin/bash' > $TRAVIS_BUILD_DIR/setFolder.sh
  - echo 'mkdir -p "$1"' >> $TRAVIS_BUILD_DIR/setFolder.sh
  - echo "chown -R :$(id -u) \"\$1\"" >> $TRAVIS_BUILD_DIR/setFolder.sh
  - echo 'chmod -R 775 "$1"' >> $TRAVIS_BUILD_DIR/setFolder.sh
  - echo 'chmod -R g+s "$1"' >> $TRAVIS_BUILD_DIR/setFolder.sh
  - chmod +x $TRAVIS_BUILD_DIR/setFolder.sh

  - $TRAVIS_BUILD_DIR/setFolder.sh .stack-work
  - $TRAVIS_BUILD_DIR/setFolder.sh .output
  - git submodule foreach --recursive "$TRAVIS_BUILD_DIR/setFolder.sh .stack-work"

  - ls -lah .
  - git submodule foreach --recursive "ls -la .stack-work"

  - rm $TRAVIS_BUILD_DIR/setFolder.sh

install:
  - |
    set -ex
    case "$BUILD" in
      linux)
        docker build --build-arg USERID=$(id -u) -t gamma_stack -f linux.Dockerfile .
        ;;
      windows)
        docker build --build-arg USERID=$(id -u) -t gamma_stack -f wine.Dockerfile .
        ;;
      osx)
        mkdir -p ~/.local/bin
        export PATH=$HOME/.local/bin:$PATH
        travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
        stack build --no-terminal --install-ghc --only-dependencies
        ;;
      docs)
        docker pull pandoc/latex:2.6
        ;;
    esac
    set +ex

script:
  - |
    set -ex
    case "$BUILD" in
      osx)
        stack install --local-bin-path ".output/$BUILD-$TAG"
        ;;
      linux|windows)
        docker container run -v $(pwd):/appdata:Z gamma_stack:latest install --allow-different-user --local-bin-path ".output/$BUILD-$TAG"
        ;;
      docs)
        make -C docs
        ;;
    esac
    set +ex

after_script:
  - docker images
  - docker ps
  - git status

after_success:
  - ls -lah ".output/$BUILD-$TAG/"
  - |
    for f in $(find .output/$BUILD-$TAG/* -maxdepth 0); do
      filename=$(basename "$f");
      ext=$([[ "$filename" = *.* ]] && echo ".${filename##*.}" || echo '');
      mv -v "$f" "$(dirname "$f")/$BUILD-$(basename "$f" $ext)-$TAG$ext";
    done

after_failure:
  - df -h
  - free -h

deploy:
  - provider: releases
    api_key:
      secure: "KcRecRX0xqKqreFsqiXxIOkIdBGyTVH3ZclV7tz/NpCCaWxLrYBFD6zwK23KR2lthI3MXXPs7S05uFQyYVfJaQP9/+LpxTHjAb0MyhzDIINBgvBlpC4qHMvWKJVM4sgp3DcxBxOeHWAfownpBQ410z5nJSsP14dTHmvtXGTY9epUSYTOUulrETu0zKoleV+B8TEdcpvdX+N6WcFiKFn2AZQaWu8bXqtSOgsMVU001Dk7D0GrzFYb6t0QSC2wYgcRdYpfD89jHLktB6oTgoc3yD1iToim/CDfnIcI4Pt6M7SuZmFzwqR6giBTmFTdHtD+hnYAra+YEHWTG7iq7gCs32sN27y9xeZ4O9ZYelp4/6esiMVm5BpkGzmtKdLVlAeIYisPW3WUCvm3k4rs2JWl6I54jU3XHz8h5yIzbZu6d1VldUO5tT+cRDQF4Xkd0qCjxkscdJJZ+lenkLifor7cDGZih0YJ8XzJZjxCOgERySXEulp/xuVmM0a8z3jWBUGyqnCwewW+klez9nj3BXRW/YFrn5N4kG/Ml0RqLQrJPAu7dCW+meNAX02m+ElsN6EYLFbp9Y/2Fal30Etsd3QN/UDKvYHTmG7v49ghcSJcWQwttdFXizwFpPqK/eX5TLKMJYatmdzRVWAkit4pGtsVrPenmVRjIt82maYNr2QCBXk="
    file_glob: true
    file: .output/$BUILD-$TAG/*
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: $BUILD =~ ^(osx|windows|linux)$
  - provider: pages
    local_dir: docs/html
    skip_cleanup: true
    github_token:
      secure: "KcRecRX0xqKqreFsqiXxIOkIdBGyTVH3ZclV7tz/NpCCaWxLrYBFD6zwK23KR2lthI3MXXPs7S05uFQyYVfJaQP9/+LpxTHjAb0MyhzDIINBgvBlpC4qHMvWKJVM4sgp3DcxBxOeHWAfownpBQ410z5nJSsP14dTHmvtXGTY9epUSYTOUulrETu0zKoleV+B8TEdcpvdX+N6WcFiKFn2AZQaWu8bXqtSOgsMVU001Dk7D0GrzFYb6t0QSC2wYgcRdYpfD89jHLktB6oTgoc3yD1iToim/CDfnIcI4Pt6M7SuZmFzwqR6giBTmFTdHtD+hnYAra+YEHWTG7iq7gCs32sN27y9xeZ4O9ZYelp4/6esiMVm5BpkGzmtKdLVlAeIYisPW3WUCvm3k4rs2JWl6I54jU3XHz8h5yIzbZu6d1VldUO5tT+cRDQF4Xkd0qCjxkscdJJZ+lenkLifor7cDGZih0YJ8XzJZjxCOgERySXEulp/xuVmM0a8z3jWBUGyqnCwewW+klez9nj3BXRW/YFrn5N4kG/Ml0RqLQrJPAu7dCW+meNAX02m+ElsN6EYLFbp9Y/2Fal30Etsd3QN/UDKvYHTmG7v49ghcSJcWQwttdFXizwFpPqK/eX5TLKMJYatmdzRVWAkit4pGtsVrPenmVRjIt82maYNr2QCBXk="
    keep_history: true
    on:
      # branch: master
      condition: $BUILD = docs