resolver: lts-5.2

packages:
- '.'
- packages/hammer/
- packages/mcl/
- packages/queryforest/
- packages/sledge/
- packages/vtk/
- packages/linear-vect/

extra-deps: []

flags:
  hammer:
    test: false
  queryforest:
    test: false

extra-package-dbs: []