name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  stack:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        stack: ["latest"]
        ghc: ["8.6.5"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'
      with:
        submodules: true

    - uses: actions/setup-haskell@v1.1
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
        enable-stack: true

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Setup env
      run: |
        echo ::set-env name=GIT_VERSION::$(git describe --abbrev=4 --dirty --always --tags)
        echo ::set-env name=HOST_OS::${{ runner.os }}

    - name: Build
      run: |
        make build

    - name: Test
      run: |
        make run-test

    - name: Build cli tool
      run: |
        make cli

    - name: Move artifacts
      run: 
        - ls -lah ".output/$HOST_OS-$GIT_VERSION/"
        - |
        for f in $(find .output/$HOST_OS-$GIT_VERSION/* -maxdepth 0); do
          filename=$(basename "$f");
          ext=$([[ "$filename" = *.* ]] && echo ".${filename##*.}" || echo '');
          mv -v "$f" "$(dirname "$f")/$HOST_OS-$(basename "$f" $ext)-$GIT_VERSION$ext";
        done

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: .output/$HOST_OS-$GIT_VERSION/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}