name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        stack: ["latest"]
        ghc: ["8.6.5"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'
      with:
        submodules: true
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - uses: actions/setup-haskell@v1.1
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
        enable-stack: true

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build
      run: |
        make build

    - name: Test
      run: |
        make run-test

    - name: Build cli tool
      run: |
        make arche-cli

    - name: Build server
      run: |
        make arche-server

    - name: Deploy application container
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      run: | 
        make deploy-server