name: Deploy and Release

on:
  push:
    branches: [master]

jobs:
  cli:
    name: cli / ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        stack: ["latest"]
        ghc: ["8.6.5"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'
      with:
        submodules: true
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - uses: actions/setup-haskell@v1.1
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
        enable-stack: true

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Setup env
      run: |
        echo ::set-env name=OUTPUT_DIR::$(make show-output-dir)

    - name: Build
      run: |
        make build

    - name: Test
      run: |
        make run-test

    - name: Build cli tool
      run: |
        make arche-cli

    - name: Move artifacts
      run: | 
        make rename-binaries

    - name: Release cli
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: $OUTPUT_DIR/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  server:
    name: server
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'
      with:
        submodules: true
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - uses: actions/setup-haskell@v1.1
      name: Setup Haskell Stack
      with:
        ghc-version: "8.6.5"
        stack-version: "latest"
        enable-stack: true

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: deploy-arche-server-stack

    - name: Build
      run: |
        make build

    - name: Test
      run: |
        make run-test

    - name: Deploy application container
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      run: | 
        make deploy-server
